In [1]:
import pandas as pd

In [6]:
df = pd.read_csv(r"D:\rebuild\pandas\layoffs.csv")
df

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
0,Google,SF Bay Area,NaN,06-04-2026,NaN,Consumer,https://www.businessinsider.com/google-clouds-...,Post-IPO,26.0,United States,06-07-2026
1,Skai,"Tel Aviv, Non-U.S.",100.0,06-03-2026,0.20,Marketing,https://www.calcalistech.com/ctechnews/article...,Series E,60.0,Israel,06-07-2026
2,Uber,SF Bay Area,NaN,06-03-2026,0.01,Transportation,https://www.cnbc.com/2026/06/03/uber-layoffs-p...,Post-IPO,25200.0,United States,06-04-2026
3,GitLab,SF Bay Area,350.0,06-02-2026,0.14,Product,https://www.wsj.com/business/earnings/gitlab-t...,Post-IPO,413.0,United States,05-11-2026
4,Aleph Farms,"Tel Aviv, Non-U.S.",10.0,06-02-2026,NaN,Food,https://www.calcalistech.com/ctechnews/article...,Unknown,119.0,Israel,06-03-2026
...,...,...,...,...,...,...,...,...,...,...,...
4430,Service,Los Angeles,NaN,3/16/2020,1.00,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,5.1,United States,8/31/2020
4431,HopSkipDrive,Los Angeles,8.0,3/13/2020,0.10,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,45.0,United States,04-03-2020
4432,Panda Squad,SF Bay Area,6.0,3/13/2020,0.75,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,1.0,United States,4/17/2020
4433,Tamara Mellon,Los Angeles,20.0,03-12-2020,0.40,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,90.0,United States,3/31/2020
4434,EasyPost,Salt Lake City,75.0,03-11-2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,12.0,United States,3/31/2020

In [7]:
df.shape

(4435, 11)

In [8]:
df.columns

Index(['company', 'location', 'total_laid_off', 'date', 'percentage_laid_off',
       'industry', 'source', 'stage', 'funds_raised', 'country', 'date_added'],
      dtype='object')

In [9]:
df.describe()

       total_laid_off  percentage_laid_off   funds_raised
count     2906.000000          2792.000000    3922.000000
mean       316.864074             0.293072     861.951529
std       1198.113760             0.303120    4575.977934
min          3.000000             0.000000       0.700000
25%         40.000000             0.100000      55.000000
50%         90.000000             0.170000     175.000000
75%        200.000000             0.330000     483.750000
max      30000.000000             1.000000  121900.000000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4435 entries, 0 to 4434
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              4435 non-null   object
 1   location             4434 non-null   object
 2   total_laid_off       2906 non-null   float64
 3   date                 4435 non-null   object
 4   percentage_laid_off  2792 non-null   float64
 5   industry             4433 non-null   object
 6   source               4432 non-null   object
 7   stage                4430 non-null   object
 8   funds_raised         3922 non-null   float64
 9   country              4433 non-null   object
 10  date_added           4435 non-null   object
dtypes: float64(3), object(8)
memory usage: 381.3+ KB

In [11]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4430    False
4431    False
4432    False
4433    False
4434    False
Length: 4435, dtype: bool

In [12]:
df.drop_duplicates(inplace=True)

In [17]:
df.isnull().sum()/len(df) *100

company                 0.000000
location                0.022548
total_laid_off         34.475761
date                    0.000000
percentage_laid_off    37.046223
industry                0.045096
source                  0.067644
stage                   0.112740
funds_raised           11.567080
country                 0.045096
date_added              0.000000
dtype: float64

In [18]:
df.dtypes

company                 object
location                object
total_laid_off         float64
date                    object
percentage_laid_off    float64
industry                object
source                  object
stage                   object
funds_raised           float64
country                 object
date_added              object
dtype: object

In [20]:
df['date']=pd.to_datetime(df['date'],errors='coerce')

In [21]:
df.dtypes

company                        object
location                       object
total_laid_off                float64
date                   datetime64[ns]
percentage_laid_off           float64
industry                       object
source                         object
stage                          object
funds_raised                  float64
country                        object
date_added                     object
dtype: object

In [27]:
df['year']=df['date'].dt.year
df['month']=df['date'].dt.month_name()
df['year'] = df['year'].astype('Int64')

In [33]:
df['company']=df['company'].str.strip()

In [35]:
df['company'].nunique()

2912

In [36]:
df

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added,year,month
0,Google,SF Bay Area,NaN,2026-06-04,NaN,Consumer,https://www.businessinsider.com/google-clouds-...,Post-IPO,26.0,United States,06-07-2026,2026,June
1,Skai,"Tel Aviv, Non-U.S.",100.0,2026-06-03,0.20,Marketing,https://www.calcalistech.com/ctechnews/article...,Series E,60.0,Israel,06-07-2026,2026,June
2,Uber,SF Bay Area,NaN,2026-06-03,0.01,Transportation,https://www.cnbc.com/2026/06/03/uber-layoffs-p...,Post-IPO,25200.0,United States,06-04-2026,2026,June
3,GitLab,SF Bay Area,350.0,2026-06-02,0.14,Product,https://www.wsj.com/business/earnings/gitlab-t...,Post-IPO,413.0,United States,05-11-2026,2026,June
4,Aleph Farms,"Tel Aviv, Non-U.S.",10.0,2026-06-02,NaN,Food,https://www.calcalistech.com/ctechnews/article...,Unknown,119.0,Israel,06-03-2026,2026,June
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4430,Service,Los Angeles,NaN,NaT,1.00,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,5.1,United States,8/31/2020,<NA>,NaN
4431,HopSkipDrive,Los Angeles,8.0,NaT,0.10,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,45.0,United States,04-03-2020,<NA>,NaN
4432,Panda Squad,SF Bay Area,6.0,NaT,0.75,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,1.0,United States,4/17/2020,<NA>,NaN
4433,Tamara Mellon,Los Angeles,20.0,2020-03-12,0.40,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,90.0,United States,3/31/2020,2020,March
4434,EasyPost,Salt Lake City,75.0,2020-03-11,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,12.0,United States,3/31/2020,2020,March

In [39]:
#Top 10 companies by layoff
df.groupby('company')['total_laid_off'].sum().sort_values(ascending=False).head(10)

company
Amazon        58124.0
Intel         43115.0
Meta          35700.0
Oracle        31294.0
Microsoft     30055.0
Dell          23650.0
Cisco         18521.0
Salesforce    16525.0
Tesla         14500.0
Google        13697.0
Name: total_laid_off, dtype: float64

In [40]:
#top10 countries by layoff 
df.groupby('country')['total_laid_off'].sum().sort_values(ascending=False).head(10)

country
United States     656788.0
India              66039.0
Germany            32055.0
United Kingdom     23354.0
Netherlands        21575.0
Sweden             20379.0
Canada             16068.0
Israel             14494.0
Brazil             11939.0
China               8190.0
Name: total_laid_off, dtype: float64

In [43]:
#WHich company layoff is 100%
df[df['percentage_laid_off'] == 1]['company']

15             Picnic
35             Parker
75         Pepper Pay
81      NeuroPixel.AI
88             Covrzy
            ...
4418          Service
4421           Ejento
4425            Popin
4429         Help.com
4430          Service
Name: company, Length: 349, dtype: object

In [48]:
#which yr has the highest layoff
df.groupby('year')['total_laid_off'].sum().sort_values(ascending=False).head(1)

year
2023    93807.0
Name: total_laid_off, dtype: float64

In [50]:
#which month has max layoff
df.groupby('month')['total_laid_off'].sum().sort_values(ascending=False)

month
January      45234.0
May          43865.0
August       37677.0
February     37544.0
November     37511.0
July         35057.0
June         26189.0
April        22926.0
March        19326.0
October      15925.0
December     14603.0
September     8818.0
Name: total_laid_off, dtype: float64

In [51]:
df

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added,year,month
0,Google,SF Bay Area,NaN,2026-06-04,NaN,Consumer,https://www.businessinsider.com/google-clouds-...,Post-IPO,26.0,United States,06-07-2026,2026,June
1,Skai,"Tel Aviv, Non-U.S.",100.0,2026-06-03,0.20,Marketing,https://www.calcalistech.com/ctechnews/article...,Series E,60.0,Israel,06-07-2026,2026,June
2,Uber,SF Bay Area,NaN,2026-06-03,0.01,Transportation,https://www.cnbc.com/2026/06/03/uber-layoffs-p...,Post-IPO,25200.0,United States,06-04-2026,2026,June
3,GitLab,SF Bay Area,350.0,2026-06-02,0.14,Product,https://www.wsj.com/business/earnings/gitlab-t...,Post-IPO,413.0,United States,05-11-2026,2026,June
4,Aleph Farms,"Tel Aviv, Non-U.S.",10.0,2026-06-02,NaN,Food,https://www.calcalistech.com/ctechnews/article...,Unknown,119.0,Israel,06-03-2026,2026,June
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4430,Service,Los Angeles,NaN,NaT,1.00,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,5.1,United States,8/31/2020,<NA>,NaN
4431,HopSkipDrive,Los Angeles,8.0,NaT,0.10,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,45.0,United States,04-03-2020,<NA>,NaN
4432,Panda Squad,SF Bay Area,6.0,NaT,0.75,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,1.0,United States,4/17/2020,<NA>,NaN
4433,Tamara Mellon,Los Angeles,20.0,2020-03-12,0.40,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,90.0,United States,3/31/2020,2020,March
4434,EasyPost,Salt Lake City,75.0,2020-03-11,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,12.0,United States,3/31/2020,2020,March

In [52]:
#which sector is suffered most
df.groupby('industry')['total_laid_off'].sum()

industry
AI                  3000.0
Aerospace           3472.0
Construction        3977.0
Consumer           97007.0
Crypto             15593.0
Data               13353.0
Education          21052.0
Energy              9880.0
Finance            67682.0
Fitness            10146.0
Food               52101.0
HR                 16157.0
Hardware          106157.0
Healthcare         39244.0
Infrastructure     24835.0
Legal               1056.0
Logistics           8165.0
Manufacturing       9280.0
Marketing          15935.0
Media              11573.0
Other             119746.0
Product             2569.0
Real Estate        20646.0
Recruiting          6732.0
Retail            106706.0
Sales              21905.0
Security           14580.0
Support             8481.0
Transportation     66002.0
Travel             23740.0
Name: total_laid_off, dtype: float64

In [55]:
#Which companies had layoffs more than once?
count=df.groupby('company').size()
count[count> 1]

company
100 Thieves    2
23andMe        3
2TM            2
2U             5
8x8            2
              ..
eToro          2
ezCater        2
iFit           3
iRobot         4
nCino          2
Length: 866, dtype: int64

In [56]:
#Industry vs Year layoffs

pd.pivot_table(df,values='total_laid_off',index='industry',columns='year',aggfunc=sum)

C:\Users\Arshad\AppData\Local\Temp\ipykernel_4132\1010018019.py:3: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df,values='total_laid_off',index='industry',columns='year',aggfunc=sum)

year              2020    2021     2022     2023     2024     2025    2026
industry
AI                 NaN     NaN      NaN     80.0      0.0    687.0   250.0
Aerospace        110.0     NaN      0.0    157.0      0.0      NaN     NaN
Construction     256.0  2434.0    223.0      0.0      NaN    114.0     NaN
Consumer        3008.0  1800.0  16832.0   2795.0   5903.0   6671.0  1267.0
Crypto             0.0     NaN   3489.0   2231.0    349.0    229.0   700.0
Data             722.0     0.0    541.0   2812.0   2035.0   1722.0    40.0
Education        137.0  1800.0   6059.0   3881.0   1718.0    248.0   255.0
Energy             NaN     NaN    605.0    195.0    959.0    400.0     NaN
Finance         3210.0     0.0   6394.0   7273.0   6197.0   1103.0  5729.0
Fitness         2221.0     0.0   4439.0    110.0    400.0     80.0   225.0
Food            2000.0    87.0   6560.0   3717.0   1069.0    600.0   103.0
HR               346.0     NaN    362.0   1315.0   2697.0   3770.0   400.0
Hardware           NaN     NaN    201.0  13276.0  18706.0   7990.0     NaN
Healthcare       619.0     NaN   4104.0   4650.0   2017.0     83.0     NaN
Infrastructure   190.0   160.0    461.0    134.0   6720.0      0.0     NaN
Legal            150.0     NaN    180.0     54.0      0.0      NaN     NaN
Logistics        290.0     NaN   1280.0   1180.0    169.0    613.0     0.0
Manufacturing      NaN     NaN      NaN    562.0   1650.0    200.0   250.0
Marketing       1251.0     NaN   2063.0   1182.0    602.0    645.0   300.0
Media            858.0    47.0    208.0   3095.0   1345.0    170.0   100.0
Other            112.0    80.0   3348.0   8713.0   5101.0  12888.0  1976.0
Product           56.0    22.0    594.0    440.0     18.0      NaN   443.0
Real Estate      547.0  2900.0   5845.0    872.0    300.0    496.0   400.0
Recruiting       753.0    13.0    157.0    961.0    269.0      NaN     NaN
Retail          2560.0   288.0   3225.0  14811.0   3720.0   1070.0  1011.0
Sales            153.0     NaN   1321.0   8680.0    559.0   1559.0   676.0
Security         197.0     NaN   1802.0   2551.0    770.0    900.0  1666.0
Support          200.0     NaN    729.0   3121.0    776.0    623.0   500.0
Transportation  5714.0     NaN   9654.0   2877.0   2509.0   2440.0   451.0
Travel          3530.0     NaN   1535.0   2082.0   1060.0     75.0   100.0

In [58]:
#layoff by company stage
df.groupby('stage')['total_laid_off'].sum().sort_values(ascending=False)

stage
Post-IPO          583018.0
Unknown            81211.0
Acquired           73295.0
Series B           32240.0
Series C           27530.0
Series D           27379.0
Series E           25414.0
Series F           16691.0
Private Equity     13080.0
Series A            9147.0
Series H            8497.0
Subsidiary          7538.0
Series G            5129.0
Series J            4700.0
Series I            3155.0
Seed                2751.0
Name: total_laid_off, dtype: float64

In [60]:
#Find companies where layoffs happened more than once AND total layoffs are very high
count=df.groupby('company').size()
total=df.groupby('company')['total_laid_off'].sum()
result=(count>1) & (total > 1000)
df.groupby('company')['total_laid_off'].sum()[result]

company
Airbnb        1930.0
Amazon       58124.0
Amdocs        2700.0
Atlassian     2450.0
Autodesk      2600.0
              ...
Yelp          1063.0
Zillow        2523.0
Zomato        1220.0
Zoom          1450.0
eBay          2540.0
Name: total_laid_off, Length: 128, dtype: float64

📊 Final Conclusion

This project on global layoffs revealed clear patterns in workforce reductions across industries, companies, countries, and time.

Key insights:

-Layoffs were heavily concentrated in a few industries, showing sector-specific impact.
A small number of companies contributed to a large share of total layoffs.
Certain countries dominated layoffs, reflecting major global tech hubs.
Layoffs peaked in specific time periods, indicating strong economic cycle effects.
Some companies experienced multiple layoff rounds, showing prolonged financial stress.

🎯 Final Insight

Overall, the analysis shows that layoffs are not random — they follow clear patterns driven by industry trends, company size, and global economic conditions.